### ISSUE TITLE
How to clean up a demo?

### ISSUE THREAD

**Issue by unphased** [vanruesc/three-demo#1]
For my demo for DepthPickerPass, the demo is the right layer of abstraction in which to implement a mousemove/mousedown handler from which to set the position for the pass to know where we want it to sample the RenderPass's depth buffer from. I would just add the event listener to document.documentElement, but there's no way to clean this up when the demo is unloaded. It seems like we may want to allow for an optional `dispose` method on the demo class so that we can clean things like this up.

**Comment by vanruesc** [comment]
> It seems like we may want to allow for an optional dispose method on the demo class so that we can clean things like this up.

The `Demo` base class has a [dispose](https://vanruesc.github.io/three-demo/public/docs/classes/demo.html#dispose) method which can be overridden to do exactly that. This method was added recently in [v4.1.0](https://github.com/vanruesc/three-demo/releases/tag/v4.1.0). Before that, cleanup was done in the `reset` method.

Here's a current [example](https://github.com/vanruesc/postprocessing/blob/db22dbc5f94b570e0a8162c80dfca9e7f245306a/demo/src/demos/BloomDemo.js#L518-L523) from the `postprocessing` repository. Note that event listeners should be added to the renderer's DOM element (canvas) for consistency reasons.

**Comment by unphased** [comment]
Thanks! I looked for dispose in the demos but I didn't look at that one, and I didnt search three-demo code thoroughly enough to find it!

Just makes me feel better being able to clean things up.
